eureka:
 client:
  register-with-eureka : true
  fetch-registry : true
  service-url:
   defaultZone: http://localhost:8091/eureka/
 instance:
  hostname: localhost
  
  
  #https://github.com/teja901/TEZ-SHOPPINGMALL-CONFIG
#spring:
# cloud:
#  config:
#   server:
#    git:
#     uri: https://github.com/teja901/TEZ-SHOPPINGMALL-CONFIG

spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/teja901/TEZ-SHOPPINGMALL-CONFIG
    
    